language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
# Currently Python 3.7 needs Ubuntu Xenial and sudo
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    # Python environment
    - "python -m pip install --upgrade setuptools pip wheel pytest coverage pytest-cov codecov"

    # Installs all package dependencies
    - "python -m pip install -e .[all]"

script:
    # Runs tests
    - "py.test -v --cov=pycosio --cov-report=term-missing"

after_success:
    # Sends coverage to codecov.io
    - "codecov"
